config/routes.rb
Rails.application.routes.draw do
  resources :quizzs do
    member do
      patch 'check'
    end
  end

  get 'home/index'
  root 'home#index'
  
  get 'quizzs/answering/1' => 'quizzs#answering', as: :answering
  
  get 'quizzs/answer/:id' => 'quizzs#answer', as: :answer
  
  post 'quizzs/:id/check' => 'quizzs#check', as: :check
  

  
end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
  validates_presence_of :question, :ans1, :ans2, :ans3
  validates_numericality_of :correctAns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:home, :answering, :answer, :check]
  # GET /quizzs
  # GET /quizzs.json
  def index
    @quizzs = Quizz.all
  end

  # GET /quizzs/1
  # GET /quizzs/1.json
  def show
  end

  # GET /quizzs/new
  def new
    @quizz = Quizz.new
  end

  # GET /quizzs/1/edit
  def edit
  end

  # POST /quizzs
  # POST /quizzs.json
  def create
    @quizz = Quizz.new(quizz_params)

    respond_to do |format|
      if @quizz.save
        format.html { redirect_to @quizz, notice: 'Quizz was successfully created.' }
        format.json { render :show, status: :created, location: @quizz }
      else
        format.html { render :new }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzs/1
  # PATCH/PUT /quizzs/1.json
  def update
    respond_to do |format|
      if @quizz.update(quizz_params)
        format.html { redirect_to @quizz, notice: 'Quizz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quizz }
      else
        format.html { render :edit }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzs/1
  # DELETE /quizzs/1.json
  def destroy
    @quizz.destroy
    respond_to do |format|
      format.html { redirect_to quizzs_url, notice: 'Quizz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # GET /quizzs/answering/1
  
  def answering
    @quizzs = Quizz.all
  end
  
  #GET /quizz/answer/1
  
  def answer
    @quizz = Quizz.find(params[:id])
  end
  
  def check
    #@count = 0
    @quizz = Quizz.find(params[:id])
	respond_to do |format|
	  if params[:ans][0].to_i == @quizz.correctAns
	    #@count += 1
	    #flash.now[:notice] = '<b>Congratulation. You gave the correct answer to the question: ' + @quizz.question + '</b>'
		#format.html {redirect_to answering_url, notice: 'Congratulation. You gave the correct answer to the question: ' + @quizz.question + 'Your score is: ' + @count.to_s}
		format.html {redirect_to answering_url, notice: 'Congratulation. You gave the correct answer to the question: ' + @quizz.question}
		#format.json { render :show, status: :ok, location: answering_path }
	  else
	    #@count = 0
	    #flash.now[:notice] = "<b style='color: red'>I am sorry but that is not the right answer to the question: " + @quizz.question + "</b>"
		#format.html {redirect_to answering_url, notice: 'I am sorry but that is not the right answer to the question: ' + @quizz.question + 'Your score is: ' + @count.to_s}
		format.html {redirect_to answering_url, notice: 'I am sorry but that is not the right answer to the question: ' + @quizz.question}
		#format.json { render :show, status: :ok, location: answering_path }
      end	  
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizz
      @quizz = Quizz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quizz_params
      params.require(:quizz).permit(:question, :ans1, :ans2, :ans3, :correctAns)
    end
	
	def authenticate
	  authenticate_or_request_with_http_basic do |name, password|
	    name == "maria" && password == "meteorologija"
	  end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%#= link_to "Visitor's Page: Answering questions", :controller => "quizzs", :action => "answering", :id =>"1" %>
<%= link_to "Visitor's Page: Answering questions", answering_path(params[:id]) %><br/>

<%= link_to "Quizz Management", quizzs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizzesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/quizzs/_form.html.erb
<%= form_for(@quizz) do |f| %>
  <% if @quizz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quizz.errors.count, "error") %> prohibited this quizz from being saved:</h2>

      <ul>
      <% @quizz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :ans1 %><br>
    <%= f.text_area :ans1 %>
  </div>
  <div class="field">
    <%= f.label :ans2 %><br>
    <%= f.text_area :ans2 %>
  </div>
  <div class="field">
    <%= f.label :ans3 %><br>
    <%= f.text_area :ans3 %>
  </div>
  <div class="field">
    <%= f.label :correctAns %><br>
    <%= f.number_field :correctAns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzs/answer.html.erb
<p>
<b>Question:</b>
<%= @quizz.question %>
</p>
<p>
<b>Ans1:</b>
<%= @quizz.ans1 %>
</p>
<p>
<b>Ans2:</b>
<%= @quizz.ans2 %>
</p>
<p>
<b>Ans3:</b>
<%= @quizz.ans3 %>
</p>
<%#= form_tag (:action => "check", :id => @quizz.id) do %>
<%#= form_tag (check_quizz_path(params[:id])) do %>
<%= form_tag (check_quizz_path) do %>
<p>
<b>The correct answer is number: </b>
<%= text_field :ans, params[:ans] %>
</p>
<p><%= submit_tag ("check") %></p>
<% end %>
<%= link_to 'Back', answering_path(params[:id]) %>

app/views/quizzs/answering.html.erb
<h2>Which question do you want to answer?</h2>
<table>
<tr>
<th>Question<th>
</tr>
<% @quizzs.each do |quizz| %>
<tr>
<td><%= quizz.question %></td>
<td><%#= link_to '<> Answer this', {:controller => "quizzs", :action => "answer", :id => quizz.id} %></td>
<td><%= link_to '<> Answer this', answer_path(quizz.id) %></td>
</tr>
<% end %>
</table>
<br />

app/views/quizzs/edit.html.erb
<h1>Editing quizz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quizz %> |
<%= link_to 'Back', quizzs_path %>

app/views/quizzs/index.html.erb
<h1>Listing quizzs</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Correctans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzs.each do |quizz| %>
      <tr>
        <td><%= quizz.question %></td>
        <td><%= quizz.ans1 %></td>
        <td><%= quizz.ans2 %></td>
        <td><%= quizz.ans3 %></td>
        <td><%= quizz.correctAns %></td>
        <td><%= link_to 'Show', quizz %></td>
        <td><%= link_to 'Edit', edit_quizz_path(quizz) %></td>
        <td><%= link_to 'Destroy', quizz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quizz', new_quizz_path %>

app/views/quizzs/new.html.erb
<h1>New quizz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzs_path %>

app/views/quizzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quizz.question %>
</p>

<p>
  <strong>Ans1:</strong>
  <%= @quizz.ans1 %>
</p>

<p>
  <strong>Ans2:</strong>
  <%= @quizz.ans2 %>
</p>

<p>
  <strong>Ans3:</strong>
  <%= @quizz.ans3 %>
</p>

<p>
  <strong>Correctans:</strong>
  <%= @quizz.correctAns %>
</p>

<%= link_to 'Edit', edit_quizz_path(@quizz) %> |
<%= link_to 'Back', quizzs_path %>